root: true
env: 
  node: true
extends:
  - 'plugin:vue/essential'
  - '@vue/airbnb'
parserOptions: 
  parser: babel-eslint
rules:
  no-lonely-if: off
  no-plusplus: off
  no-restricted-syntax: off
  max-len: off
