root: true
env: 
  node: true
extends:
  - 'plugin:vue/essential'
  - '@vue/airbnb'
parserOptions: 
  parser: babel-eslint
globals:
  STATIC_BASE: readonly
  ROUTER_BASE: readonly
rules:
  guard-for-in: off
  no-lonely-if: off
  no-nested-ternary: off
  no-plusplus: off
  no-restricted-syntax: off
  max-len: off
  prefer-destructuring: off
